let name = prompt("ism kiriting")
let age = prompt("yosh kiriting")
let maktab = prompt("maktabingiz raqamini kiriting")
let manzil= prompt("yashash manzilingizni kiriting")
let familiya = prompt("familiyangizni kiriting")
let yil_sana = prompt("nechinchi yilda tug'ulgansan")
let marsdagi_ustoz = prompt("ustozingizni kirinting")
console.log(name)
console.log(age)
console.log(maktab)
console.log(manzil)
console.log(familiya)
console.log(yil_sana)
console.log(marsdagi_ustoz)